### ISSUE TITLE
Consult how to realize Sim.

### ISSUE THREAD

**Issue by L-SY** [utiasDSL/upright#1]
- Thanks for your open source, your method is so elegant.I want try to recurrent it.
- Follow your step, I have complete the job of install and compile.
- Could you give me a more detailed way to sim this paper.Thank you very much!

**Comment by L-SY** [comment]
Now the problem looks like it's missing a environment variable.
```
root@lsy:/home/catkin_ws/src/upright/dsl__projects__tray_balance/upright_sim/src/upright_sim# python3 simulation.py --config ../../../upright_cmd/config/simulation.yaml 
pybullet build time: Nov 28 2023 23:51:11
Traceback (most recent call last):
  File "simulation.py", line 7, in <module>
    from mobile_manipulation_central.simulation import BulletSimulation
  File "/home/catkin_ws/devel/lib/python3/dist-packages/mobile_manipulation_central/__init__.py", line 34, in <module>
    exec(__fh.read())
  File "<string>", line 45, in <module>
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'MOBILE_MANIPULATION_CENTRAL_BAG_DIR'

```

**Comment by L-SY** [comment]
When I use command

```
home/catkin_ws/src/upright/dsl__projects__tray_balance/upright_cmd/scripts/simulations# python3 mpc_sim.py --config ../../../upright_cmd/config/playground/ur10_demo.yaml
```

it error like 

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/catkin_ws/src/upright/dsl__projects__tray_balance/upright_assets/thing/xacro/cartesian_base_joints.urdf.xacro'
```

I check zhe pr, the file seems do not exist.

**Comment by adamheins** [comment]
Some of the instructions and files are outdated. Thanks for pointing this out! I will get back to you shortly with some updates.

**Comment by L-SY** [comment]
> When I use command
> 
> ```
> home/catkin_ws/src/upright/dsl__projects__tray_balance/upright_cmd/scripts/simulations# python3 mpc_sim.py --config ../../../upright_cmd/config/playground/ur10_demo.yaml
> ```
> 
> it error like
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: '/home/catkin_ws/src/upright/dsl__projects__tray_balance/upright_assets/thing/xacro/cartesian_base_joints.urdf.xacro'
> ```
> 
> I check zhe pr, the file seems do not exist.

These missing file such as .xacro and .urdf  are located at  https://github.com/utiasDSL/mobile_manipulation_central.

**Comment by L-SY** [comment]
> Some of the instructions and files are outdated. Thanks for pointing this out! I will get back to you shortly with some updates.

**Comment by L-SY** [comment]
> Some of the instructions and files are outdated. Thanks for pointing this out! I will get back to you shortly with some updates.

Looking forward to seeing new instructions, especially those related to simulation!

**Comment by L-SY** [comment]
> I pushed a commit that cleans up the `upright_cmd/config/playground/*_demo.yaml` simulations, and also added a bit more information to the Simulation section of the README; I would suggest trying either `thing_demo.yaml` or `ur10_demo.yaml`. I am hoping to clean up this project a bit more substantially in the coming months (including better documentation), but this will take some time.

Thanks it did work! Looking forward to a more complete work！
![Screenshot from 2024-02-27 09-56-36](https://github.com/utiasDSL/upright/assets/54620791/5948e209-1b81-4dbd-a4e9-090f89ecf0a8)

**Comment by adamheins** [comment]
Great, I'm glad it's working for you!

**Comment by DiomandLEE** [comment]
Could you please give us a docker for this repo
