### ISSUE TITLE
Ask about .py and .cpp 's function.

### ISSUE THREAD

**Issue by L-SY** [utiasDSL/upright#2]
Hello!
  I see both cpp and python code in your upright_control and upright_ros_interface,
Is the python code only used to simulatewith Pybullet, and can the python code be removed if other simulation tools are used, such as Webots and Gazebo?
  Hope to hear from you!!

**Comment by adamheins** [comment]
At the moment a lot of the parsing of configuration options, which notably includes parsing the configuration of the balanced objects, is done purely in Python, even when using the C++ controllers in `upright_ros_interface`. Therefore both Python and C++ components are currently required.

**Comment by adamheins** [comment]
Ideally, all the machinery would be written in C++ with bindings only to support simulation. However, prototyping in Python is faster than C++, so some of the code (the parsing in particular) was written in Python and it would take a fair bit of time and effort to translate it.

**Comment by adamheins** [comment]
I'll go ahead and close this; feel free to re-open if you have more questions.
