### ISSUE TITLE
simulation can not run 

### ISSUE THREAD

**Issue by DiomandLEE** [utiasDSL/upright#3]
![Screenshot from 2024-04-19 20-35-43](https://github.com/utiasDSL/upright/assets/87216511/803a961e-1a7e-4e70-9551-e6997f06ec8d)
i can not run the simulation, could you please give a docker about this project, or give me the whole install process, it confuse me a week!!! Thanks

**Comment by adamheins** [comment]
The error you ran into in that screenshot is that the environment variable `MOBILE_MANIPULATION_CENTRAL_BAG_DIR` is not set; it should be a directory path in which to save bag files. However, I just pushed a change to `mobile_manipulation_central`'s main branch that does not require that variable to be set unless you are actually recording a bag. That might fix your issue.

Regarding a Docker file, I think that would be a good idea. I've put it on my todo list, but I'm quite busy at the moment so I'm not sure when I will get to it.

**Comment by DiomandLEE** [comment]
> The error you ran into in that screenshot is that the environment variable `MOBILE_MANIPULATION_CENTRAL_BAG_DIR` is not set; it should be a directory path in which to save bag files. However, I just pushed a change to `mobile_manipulation_central`'s main branch that does not require that variable to be set unless you are actually recording a bag. That might fix your issue.
> 
> Regarding a Docker file, I think that would be a good idea. I've put it on my todo list, but I'm quite busy at the moment so I'm not sure when I will get to it.

Moreover, when importing packages like upright_core, I encounter the same error. I really don't understand why this is happening. Sorry for the inconvenience, and I'm very grateful for your response amidst your busy schedule!

**Comment by DiomandLEE** [comment]
Moreover, when importing packages like upright_core, I encounter the same error. I really don't understand why this is happening. Sorry for the inconvenience, and I'm very grateful for your response amidst your busy schedule!

**Comment by adamheins** [comment]
Try updating [mobile_manipulation_central](https://github.com/utiasDSL/mobile_manipulation_central) to the latest commit.
