### ISSUE TITLE
Help Needed with Smooth Trajectory Following in Robotic Arm Control

### ISSUE THREAD

**Issue by L-SY** [utiasDSL/upright#5]
Dear adamheins,

I am using your `InertialAlignment` cost function to achieve balance of the end-effector object. In Rviz, it appears to work well, but I encounter some issues when implementing it on a real robotic arm. How do you achieve such smooth trajectory following?

I am facing challenges with the following:

1. **Handling Acceleration in MPC State:**
    - In the MPC state, I have position, velocity, and acceleration, with jerk as the input.
    - To follow the trajectory, how should I handle the acceleration? Using `delta_velocity / dt` seems unstable, possibly due to the instability of `ros::Time`.

2. **Trajectory Following Method:**
    - What method do you use for trajectory following?
    - I am using Pinocchio for gravity compensation and applying Kd and Kp to follow position and velocity.
    - However, the performance is poor, likely due to inaccuracies in the URDF model and the complexities introduced by friction and other real-world factors.

Could you please share your approach for achieving such smooth trajectory following in real robotic arms?

I appreciate your time and look forward to your response. Thank you very much!

Best regards,

**Comment by adamheins** [comment]
1. I would suggest using a Kalman filter to estimate the joint velocity and acceleration from joint position measurements. This will require some tuning, but is the approach we use.
2. The UR10 arm that we use directly accepts joint velocity commands and tracks them with high accuracy. If your robot is torque-controlled, then your tracking performance will only be as good as the dynamic model you have. In that case, you may also consider changing the optimal control problem from using a kinematic model of the robot to a dynamic model that optimizes over torques (possibly including torque derivatives as well for smoothness).
