### ISSUE TITLE
Question About the Real

### ISSUE THREAD

**Issue by DiomandLEE** [utiasDSL/upright#6]
Regarding the real machine experiments: I want to deploy your code on my experimental equipment, so I read your '[mrt_node.cpp](https://github.com/utiasDSL/upright/blob/main/upright_ros_interface/src/mrt_node.cpp)'. I have a few questions:
Why is the '[Kalman filter](https://github.com/utiasDSL/upright/blob/main/upright_ros_interface/src/mrt_node.cpp#L157)' applied to the mobile manipulator and not to the projectile?
What do '[mpc_plan_pub](https://github.com/utiasDSL/upright/blob/main/upright_ros_interface/src/mrt_node.cpp#L301)' and '[cmd_pub](https://github.com/utiasDSL/upright/blob/main/upright_ros_interface/src/mrt_node.cpp#L312)' publish? I couldn't find any corresponding subscribers.
Since cmd_pub already exists, what is the code from '[this line](https://github.com/utiasDSL/upright/blob/main/upright_ros_interface/src/mrt_node.cpp#L337)' doing? Why define cmd_vel again?
And why use evaluatePolicy()? difference from rolloutPolicy()?

**Comment by adamheins** [comment]
* We use two separate Kalman filters, one for the robot and one for the projectile. The one for the projectile can be found [here](https://github.com/utiasDSL/mobile_manipulation_central/blob/main/include/mobile_manipulation_central/projectile.h).
* `mpc_plan_pub` and `cmd_pub` just publish the optimized trajectory and the integrated command, respectively, for debugging purposes. Basically we record them as extra data in our rosbag to better understand the controller.
* The line `u_cmd = Kx * (xd - x).head(r.x) + u.head(r.u);` is a simple affine feedback control law to track the trajectory optimized by MPC, which can be tuned by the user. We actually just set `Kx=0` and use the feedback control law computed by OCS2, which is what `evaluatePolicy` computes for us. This is in contrast to `rolloutPolicy`, which I think just gets you the next state and input from the current policy.

**Comment by DiomandLEE** [comment]
> * We use two separate Kalman filters, one for the robot and one for the projectile. The one for the projectile can be found [here](https://github.com/utiasDSL/mobile_manipulation_central/blob/main/include/mobile_manipulation_central/projectile.h).
> * `mpc_plan_pub` and `cmd_pub` just publish the optimized trajectory and the integrated command, respectively, for debugging purposes. Basically we record them as extra data in our rosbag to better understand the controller.
> * The line `u_cmd = Kx * (xd - x).head(r.x) + u.head(r.u);` is a simple affine feedback control law to track the trajectory optimized by MPC, which can be tuned by the user. We actually just set `Kx=0` and use the feedback control law computed by OCS2, which is what `evaluatePolicy` computes for us. This is in contrast to `rolloutPolicy`, which I think just gets you the next state and input from the current policy.

Certainly! Here are the three responses formatted for a GitHub issue reply, with the URLs turned into links corresponding to the respective code file names:

---

1. I found exponential smoothing in [ridgeback_vicon_estimator_node.cpp](https://github.com/utiasDSL/mobile_manipulation_central/blob/main/src/ridgeback_vicon_estimator_node.cpp#L113). Why is exponential smoothing used in this context? Is it to avoid inaccuracies in velocity values estimated from the first-order difference of positions? In the `mrt_ros_interface` Kalman filter, what kinematic information is used to estimate what kinematic information? Here is the [mrt_node.cpp corresponding line](https://github.com/utiasDSL/upright/blob/main/upright_ros_interface/src/mrt_node.cpp#L232) link.

2. I found the code subscribing to `mpc_plan` in [mpc_sim_ros.py](https://github.com/utiasDSL/upright/blob/main/upright_cmd/scripts/simulations/mpc_sim_ros.py#L121). It is in a Python file and seems to be used for PyBullet simulation？used for showing details for debug？

3. The affine feedback control you mentioned `u_cmd = Kx * (xd - x).head(r.x) + u.head(r.u);` seems similar to a feedforward PID control with only a proportional term: $u(t) = u_{\text{ff}}(t) + K_p e(t) + K_i \int_0^t e(\tau) \, d\tau + K_d \frac{de(t)}{dt}$
. I'm not sure if my understanding is correct. 

In OCS2, I am very confused about this. Here is the link to the corresponding file in OCS2: [MRT_ROS_Dummy_Loop.cpp](https://github.com/leggedrobotics/ocs2/blob/main/ocs2_ros_interfaces/src/mrt/MRT_ROS_Dummy_Loop.cpp#L171).
 My previous understanding was that `evaluatePolicy()` obtains the optimal state and input through interpolation, whereas I don't understand `rolloutPolicy()`. My guess is that it obtains the optimal state and input considering only the dynamic equations?

And how do you know `evaluatePolicy()` used the feedback control law? I don't find the corresponding comments, And how should I understand "This is in contrast to `rolloutPolicy`, which I think just gets you the next state and input from the current policy."?

After reading your explanation, it seems `evaluatePolicy()` considers the feedback control matrix, so \( Kx = 0 \), while `rolloutPolicy` does not consider it, so \( Kx \neq 0 \). I'm not sure if this understanding is correct.

Moreover, the concept of `rollout` in OCS2 is somewhat abstract and difficult to grasp. Deploying it on a real machine is indeed a challenge, lol,o(╥﹏╥)o

---

**Comment by DiomandLEE** [comment]
> * We use two separate Kalman filters, one for the robot and one for the projectile. The one for the projectile can be found [here](https://github.com/utiasDSL/mobile_manipulation_central/blob/main/include/mobile_manipulation_central/projectile.h).
> * `mpc_plan_pub` and `cmd_pub` just publish the optimized trajectory and the integrated command, respectively, for debugging purposes. Basically we record them as extra data in our rosbag to better understand the controller.
> * The line `u_cmd = Kx * (xd - x).head(r.x) + u.head(r.u);` is a simple affine feedback control law to track the trajectory optimized by MPC, which can be tuned by the user. We actually just set `Kx=0` and use the feedback control law computed by OCS2, which is what `evaluatePolicy` computes for us. This is in contrast to `rolloutPolicy`, which I think just gets you the next state and input from the current policy.

---

1. I found exponential smoothing in [ridgeback_vicon_estimator_node.cpp](https://github.com/utiasDSL/mobile_manipulation_central/blob/main/src/ridgeback_vicon_estimator_node.cpp#L113). Why is exponential smoothing used in this context? Is it to avoid inaccuracies in velocity values estimated from the first-order difference of positions? In the `mrt_ros`  [Kalman filter](https://github.com/utiasDSL/upright/blob/main/upright_ros_interface/src/mrt_node.cpp#L232) , what kinematic information is used to estimate what kinematic information? 

2. I found the code subscribing to `mpc_plan` in [mpc_sim_ros.py](https://github.com/utiasDSL/upright/blob/main/upright_cmd/scripts/simulations/mpc_sim_ros.py#L121). It is in a Python file and seems to be used for PyBullet simulation？used for showing details for debug？

3. The affine feedback control you mentioned `u_cmd = Kx * (xd - x).head(r.x) + u.head(r.u);` seems similar to a feedforward PID control with only a proportional term: $u(t) = u_{\text{ff}}(t) + K_p e(t) + K_i \int_0^t e(\tau) \, d\tau + K_d \frac{de(t)}{dt}$
. I'm not sure if my understanding is correct. 

In OCS2, I am very confused about this. Here is the link to the corresponding file in OCS2: [evaluatePolicy() and rolloutPolicy()](https://github.com/leggedrobotics/ocs2/blob/main/ocs2_ros_interfaces/src/mrt/MRT_ROS_Dummy_Loop.cpp#L171).
 My previous understanding was that `evaluatePolicy()` obtains the optimal state and input through interpolation, whereas I don't understand `rolloutPolicy()`. My guess is that it obtains the optimal state and input considering only the dynamic equations?

And how do you know `evaluatePolicy()` used the feedback control law? I don't find the corresponding comments, And how should I understand "This is in contrast to `rolloutPolicy`, which I think just gets you the next state and input from the current policy."?

After reading your explanation, it seems `evaluatePolicy()` considers the feedback control matrix, so \( Kx = 0 \), while `rolloutPolicy` does not consider it, so \( $Kx \neq 0 $\). I'm not sure if this understanding is correct.

Moreover, the concept of `rollout` in OCS2 is somewhat abstract and difficult to grasp. Deploying it on a real machine is indeed a challenge, lol,o(╥﹏╥)o

**Comment by adamheins** [comment]
1. Yes, the exponential smoother is used to filter out noise in the velocity from noisy numerical differentiation. In the Kalman filter in the MRT node, we use the robot joint positions to estimate the current joint velocity and acceleration. Note that the exponentially-smoothed velocities are not used in this project.
2. Yes, that is some old experimental/debugging code, designed to visualize the plans generated by MPC.
3. Yes, basically they are both linear controllers. Note that while we only have a gain on the state `x`, the state itself contains multiple derivatives (velocity and acceleration).

Regarding the difference between `evaluatePolicy` and `rolloutPolicy`: if you look [here](https://github.com/leggedrobotics/ocs2/blob/main/ocs2_mpc/include/ocs2_mpc/MRT_BASE.h#L126), `evaluatePolicy` just computes optimized state and control output at the given time and state using the most recently computed policy, whereas `rolloutPolicy` actually forward-simulates the trajectory using the current policy ("rolls it out") from the provided state up to a given time (which can be done using RK4 or other integrators).

**Comment by DiomandLEE** [comment]
> 1. Yes, the exponential smoother is used to filter out noise in the velocity from noisy numerical differentiation. In the Kalman filter in the MRT node, we use the robot joint positions to estimate the current joint velocity and acceleration. Note that the exponentially-smoothed velocities are not used in this project.
> 2. Yes, that is some old experimental/debugging code, designed to visualize the plans generated by MPC.
> 3. Yes, basically they are both linear controllers. Note that while we only have a gain on the state `x`, the state itself contains multiple derivatives (velocity and acceleration).
> 
> Regarding the difference between `evaluatePolicy` and `rolloutPolicy`: if you look [here](https://github.com/leggedrobotics/ocs2/blob/main/ocs2_mpc/include/ocs2_mpc/MRT_BASE.h#L126), `evaluatePolicy` just computes optimized state and control output at the given time and state using the most recently computed policy, whereas `rolloutPolicy` actually forward-simulates the trajectory using the current policy ("rolls it out") from the provided state up to a given time (which can be done using RK4 or other integrators).

---------------------------------------------------------------------------------------------------------------------
1.It turns out that this project does not use exponential smoothing for velocity estimation, but rather employs Kalman filtering for all estimates.
2.Yes, I understand that the state 𝑥 includes position, velocity, and acceleration, and the input in your project should be jerk?
3.I did see the comments, but I am still confused. It seems like rolloutPolicy is used for simulation and directly gets the policy published by MPC, while evaluatePolicy is calculated through interpolation or some other method. However, they seem very similar to me. Maybe when useFeedbackPolicy = false, they are the same, and when it's true, evaluatePolicy should be used. Anyway, maybe choosing evaluatePolicy is the right way to go, haha

**Comment by adamheins** [comment]
Yep, you're correct about the state, and that the input is the jerk.

To be honest I'm also not really sure about the exact differences between `rolloutPolicy` and `evaluatePolicy`, I always just used the latter.

**Comment by DiomandLEE** [comment]
Thank you for your reply. I will close this issue.^_^
