### ISSUE TITLE
Simulation Sudden Obstacle Method for Help

### ISSUE THREAD

**Issue by DiomandLEE** [utiasDSL/upright#8]
Hello, sorry to bother you again. I am curious about how you implemented obstacle avoidance for suddenly appearing obstacles in your simulation. From our previous conversations, I have learned how to augment the state vector to avoid dynamic obstacles, but I haven't figured out a solution for this type of sudden obstacle. Global search for '['sudden.'](https://github.com/utiasDSL/upright/blob/main/upright_cmd/config/obstacles/sudden.yaml#L75)', I found the '[sudden.yaml](https://github.com/utiasDSL/upright/blob/main/upright_cmd/config/obstacles/sudden.yaml#L75)', "But I haven't discovered how to use it, so I searched for 'modes.' Since my ability to read Python is relatively weak, I chose to look through the C++ files instead.('[modes search result in cpp](https://github.com/utiasDSL/upright/blob/main/upright_ros_interface/src/mrt_node.cpp#L275)') In this context, it seems like the state of the dynamic obstacle was forcefully changed, but is it appropriate to directly insert it into `evaluatePolicy(t, x, xd, u, mode)`? Because the policy has already been calculated before this step. Of course, these are just my guesses, as "the sudden case" is written in simulation by Python, not in C++. I'm very eager to hear your thoughts.

**Comment by adamheins** [comment]
It is essentially just changing the state of the obstacle at some pre-specified time (that the controller does not know about beforehand). We send this updated state immediately to `evaluatePolicy` because we want to ensure that our policy can actually deal with a sudden state change like this, even though it was not prepared for it.

**Comment by DiomandLEE** [comment]
> It is essentially just changing the state of the obstacle at some pre-specified time (that the controller does not know about beforehand). We send this updated state immediately to `evaluatePolicy` because we want to ensure that our policy can actually deal with a sudden state change like this, even though it was not prepared for it.

——————————————————————————————————————————————————————
Sure, here’s the translation:

---

1. In the obstacle avoidance effect shown in your simulation, I noticed that every part of the whole mobile manipulator avoids sudden obstacles. We previously discussed that this was achieved through OCS2's self-collision avoidance. Did you define collision primitives as in the OCS2 mobile manipulator example? If so, in which URDF file are they defined?

2. Since your simulation is programmed in Python, could you tell me in which file and on which line of code the sudden obstacle handling is implemented?

3. You mentioned that you use `evaluatePolicy()` for testing “your policy can actually deal with a sudden state change like this, even though it was not prepared for it”. What are the testing results?

**Comment by adamheins** [comment]
1. We programmatically build the dynamic obstacle (this includes both projectiles and the "sudden" obstacles) geometry from the config files. See the code [here](https://github.com/utiasDSL/upright/blob/main/upright_control/src/controller_interface.cpp#L195-L212).
2. Take a look at the [BulletDynamicObstacle class](https://github.com/utiasDSL/upright/blob/d7a2ebf3e9b6e50a321348c79bd2ddc12c866dd2/upright_sim/src/upright_sim/simulation.py#L307) as well as [this logic](https://github.com/utiasDSL/upright/blob/main/upright_sim/src/upright_sim/simulation.py#L418-L426) to change the obstacle modes as the simulation is stepped forward in time.
3. See section VIII.B.1 of the [paper](https://arxiv.org/pdf/2305.17484). Basically, we found that in this scenario, the controller was able to quickly pull the system out of the sudden collision without dropping the object.

**Comment by DiomandLEE** [comment]
1. Yes, I’ve noticed that code, but since I’m unable to compile it successfully, I can’t see the exact file location of the URDF file with the collision primitives in the configuration files. Could you provide the exact urdf file location for collison avoidance? And I saw  the figure8 top right in the paper, Is it allowed by URDF to have multiple collision spheres on a single link? How is this achieved?
2. And '[this logic](https://github.com/utiasDSL/upright/blob/main/upright_sim/src/upright_sim/simulation.py#L418-L426)' ,why the function called resetBasePositionAndOrientation(), only modify the base ?
3. For the calibration of the UR5-RidgeBack in Vicon, how did you achieve it?

**Comment by adamheins** [comment]
1. The URDF for the robot's collision spheres are defined in [this URDF](https://github.com/utiasDSL/upright/blob/main/upright_assets/thing/xacro/collision_links.urdf.xacro), but as I said before the dynamic obstacles are *not* encoded in a URDF, they are generated programmatically. I'm not sure what you mean by the figure8, but yes, you can attach as many links (which can be collision spheres) to each joint as you want in a URDF.
2. The dynamic obstacles are just single rigid bodies, so they only have a base component.
3. I'm not sure what you mean - what quantities do you want to calibrate?

**Comment by adamheins** [comment]
With regard to calibration, for our mobile manipulation setup, the general procedure is:
1. ensure the robot's base and the tray are have markers to be tracked by a motion capture system
2. grip the tray with the robot's end effector
3. move to a sequence of desired joint positions and measure the tray's pose with motion capture
4. perform a nonlinear optimization on SE(3) to compute the transform between the end effector and tray based on the measured data, and in our case also between the robot's base and the arm.

Our code to collect the required calibration data is [here](https://github.com/utiasDSL/mobile_manipulation_central/blob/main/scripts/calibration/collect_arm_calibration_data.py), while the subsequent optimization procedure is [here](https://github.com/utiasDSL/mobile_manipulation_central/blob/main/scripts/calibration/calibrate_ee.py). You'll probably have to adapt things a bit for your setup.
